### ISSUE TITLE
USB support?

### ISSUE THREAD

**Issue by ghost** [FIX94/wii-ds-rom-sender#5]
Last night I was trying to get Pokemon White 2 on my 3DS, and since I don't have an SD card (well, not one that works, my adapter is broken too), I tried it on a USB drive and it didn't work. I even looked through some of your code and put the "srl" folder in the root of the drive, but still nothing. But, I also saw `fatInitDefault()`, which lead me to believe that it is trying to access the SD card, what I think is the default.

So, my main question is that are you planning to add USB support to this? This project looks promising to me but I can't use it because of the lack of USB support.

**Comment by FIX94** [comment]
you can literally only transfer special made files with a max size of 4mb since it all has to fit into the ds ram at once, you cant just load full games...

**Comment by ghost** [comment]
Ah, my bad.
