### ISSUE TITLE
 I have a problem with this homebrew

### ISSUE THREAD

**Issue by Nintendero65** [FIX94/wii-ds-rom-sender#8]
Well this is the error:
I found out about this program and I was very happy but at the moment of selecting the rom de gbc I get the error that is in the image ....
I await your answer goodbye
![dsc_0012](https://user-images.githubusercontent.com/38362260/38754745-658f9a5e-3f39-11e8-8b2c-7861a5c95998.JPG)

**Comment by FIX94** [comment]
gba files arent even supported, you should've seen that directly from the readme on the first page, and also that error says that that file is also too big to even fit into the tiny ds ram, files can only be sent fully in one go.
